### ISSUE TITLE
Compact simulator iteration printout

### ISSUE THREAD

**Issue by dhodcz2** [dhodcz2/ECE466_Group3_Project1#5]
In [circuit_simulator.py](https://github.com/dhodcz2/ECE466_Group3_Project1/tree/circuit_simulator) you will implement a smarter printout of each iteration before. Currently, information is printed vertically, wasting much space in the.

You will [dynamically clear](https://stackoverflow.com/questions/517970/how-to-clear-the-interpreter-console) the console, and updating it with a compact view of changing values within the nodes of the CircuitSimulator. The CircuitSimulator.nodes are already iterated in order alphabetically, going through inputs, intermediates, and then outputs. You may need to create some sort of Iteration class that can take another Iteration in a function, combining the values to form a new string.
Here is the idea:

```
type    variable    logic   inputs  Initial 1   
input       a                           1           
input       b                           1
input       c                           1
input       d                           1
wire        e       NAND    a, b        U   0   
wire        f       AND     b, c        U   1
wire        g       NOT     c           U   0
output      x       OR      e, f        U       
output      y       AND     f, g, d     U      

```
On the next iteration, the printout will clear and instead show:
```
type    variable    logic   inputs  Initial 1   2   
input       a                           1           
input       b                           1
input       c                           1
input       d                           1
wire        e       NAND    a, b        U   0   
wire        f       AND     b, c        U   1
wire        g       NOT     c           U   0
output      x       OR      e, f        U       1
output      y       AND     f, g, d     U       0
```

**Comment by TeamDivisionOne** [comment]
Fixed output formatting
